# Jekyll Configuration
exclude: ["photo.js", "style.css", "Rakefile", "README"]

# Site configuration
title: One Nite Band
photo-root-a: //photos1.oneniteband.com
photo-root-b: //photos2.oneniteband.com
photo-root-c: //photos3.oneniteband.com
photo-root-d: //photos4.oneniteband.com
